@baseUrl = http://localhost:4000/auth

### Check Health
GET {{baseUrl}}

### Sign Up
# @name sign-up
POST {{baseUrl}}/sign-up
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "User5",
    "email": "test_user5@example.com",
    "password": "StrongPass"
}

### Verify OTP
POST {{baseUrl}}/verify
Content-Type: application/json

{
    "sessionId": "c463b2d2-5899-4707-819c-e0c52b7de603",
    "otp": "382395"
}

### Resend OTP
POST {{baseUrl}}/auth/resend-otp
Content-Type: application/json

{
    "sessionId": "374eb4d8-d3b2-49ac-a78d-f545e1240737"
}

### Login
# @name login
POST {{baseUrl}}/sign-in
Content-Type: application/json

{
    "email": "test_user3@example.com",
    "password": "StrongPass"
}