import "@estore/components";
import "@estore/components/css";
import { cn } from "@estore/utils";
import { Inter } from "next/font/google";
import { Provider } from "./provider";

export const metadata = {
  title: "Welcome to user-ui",
  description: "Generated by create-nx-workspace",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn(inter.className, "size-full")}>
      <body className="size-full bg-[#EDEFEF]">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
